#!/usr/bin/env bash

if [ "${ENHANCED_COUNTDOWN_CONTEXT_LOADED:-0}" = "1" ]; then
  return 0
fi
ENHANCED_COUNTDOWN_CONTEXT_LOADED=1

ENHANCED_COUNTDOWN_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENHANCED_COUNTDOWN_PROJECT_ROOT="$(cd "$ENHANCED_COUNTDOWN_LIB_DIR/../.." && pwd)"

if [ -f "$ENHANCED_COUNTDOWN_PROJECT_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$ENHANCED_COUNTDOWN_PROJECT_ROOT/.env"
  set +a
fi

ADOFAI_DIR="${ADOFAI_DIR:-$HOME/Library/Application Support/Steam/steamapps/common/A Dance of Fire and Ice}"
ADOFAI_MODS_DIR="${ADOFAI_MODS_DIR:-$ADOFAI_DIR/Mods}"
ADOFAI_MANAGED="${ADOFAI_MANAGED:-$ADOFAI_DIR/ADanceOfFireAndIce.app/Contents/Resources/Data/Managed}"

DOTNET_ROOT="${DOTNET_ROOT:-$HOME/.dotnet}"
DOTNET_ROOT_ARM64="${DOTNET_ROOT_ARM64:-$DOTNET_ROOT}"
DOTNET_EXE="${DOTNET_EXE:-$DOTNET_ROOT/dotnet}"

UNITY_MOD_MANAGER_DLL="${UNITY_MOD_MANAGER_DLL:-$ADOFAI_MANAGED/UnityModManager/UnityModManager.dll}"
HARMONY_DLL="${HARMONY_DLL:-$ADOFAI_MANAGED/UnityModManager/0Harmony.dll}"

ENHANCED_COUNTDOWN_BUILD_OUTPUT="${ENHANCED_COUNTDOWN_BUILD_DIR:-$ENHANCED_COUNTDOWN_PROJECT_ROOT/build/EnhancedCountdown}"
ENHANCED_COUNTDOWN_ASSET_SOURCE="$ENHANCED_COUNTDOWN_PROJECT_ROOT/EnhancedCountdown/Assets"
ENHANCED_COUNTDOWN_BOOTSTRAP_BUILD_OUTPUT="${ENHANCED_COUNTDOWN_BOOTSTRAP_BUILD_DIR:-$ENHANCED_COUNTDOWN_PROJECT_ROOT/build/EnhancedCountdown.Bootstrap}"
ENHANCED_COUNTDOWN_UPDATE_ENGINE_BUILD_OUTPUT="${ENHANCED_COUNTDOWN_UPDATE_ENGINE_BUILD_DIR:-$ENHANCED_COUNTDOWN_PROJECT_ROOT/build/EnhancedCountdown.UpdateEngine}"
ENHANCED_COUNTDOWN_INSTALL_PATH="${ENHANCED_COUNTDOWN_INSTALL_DIR:-$ADOFAI_MODS_DIR/EnhancedCountdown}"
ENHANCED_COUNTDOWN_PACKAGE_BUILD_ROOT="${ENHANCED_COUNTDOWN_PACKAGE_ROOT:-$ENHANCED_COUNTDOWN_PROJECT_ROOT/build/package}"
ENHANCED_COUNTDOWN_PACKAGE_STAGE="$ENHANCED_COUNTDOWN_PACKAGE_BUILD_ROOT/EnhancedCountdown"
ENHANCED_COUNTDOWN_PACKAGE_ZIP_PATH="${ENHANCED_COUNTDOWN_PACKAGE_ZIP:-$ENHANCED_COUNTDOWN_PROJECT_ROOT/build/EnhancedCountdown.zip}"
ENHANCED_COUNTDOWN_UPDATE_MANIFEST_PATH="${ENHANCED_COUNTDOWN_UPDATE_MANIFEST:-$ENHANCED_COUNTDOWN_PROJECT_ROOT/build/EnhancedCountdown.update.json}"

export ENHANCED_COUNTDOWN_PROJECT_ROOT
export ADOFAI_DIR ADOFAI_MODS_DIR ADOFAI_MANAGED
export DOTNET_ROOT DOTNET_ROOT_ARM64 DOTNET_EXE
export UNITY_MOD_MANAGER_DLL HARMONY_DLL
export ENHANCED_COUNTDOWN_BUILD_OUTPUT ENHANCED_COUNTDOWN_ASSET_SOURCE ENHANCED_COUNTDOWN_INSTALL_PATH
export ENHANCED_COUNTDOWN_BOOTSTRAP_BUILD_OUTPUT ENHANCED_COUNTDOWN_UPDATE_ENGINE_BUILD_OUTPUT
export ENHANCED_COUNTDOWN_PACKAGE_BUILD_ROOT ENHANCED_COUNTDOWN_PACKAGE_STAGE
export ENHANCED_COUNTDOWN_PACKAGE_ZIP_PATH ENHANCED_COUNTDOWN_UPDATE_MANIFEST_PATH
