#!/usr/bin/env bash

if [ "${REMOVE_COUNTDOWN_CONTEXT_LOADED:-0}" = "1" ]; then
  return 0
fi
REMOVE_COUNTDOWN_CONTEXT_LOADED=1

REMOVE_COUNTDOWN_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REMOVE_COUNTDOWN_PROJECT_ROOT="$(cd "$REMOVE_COUNTDOWN_LIB_DIR/../.." && pwd)"

if [ -f "$REMOVE_COUNTDOWN_PROJECT_ROOT/.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$REMOVE_COUNTDOWN_PROJECT_ROOT/.env"
  set +a
fi

ADOFAI_DIR="${ADOFAI_DIR:-$HOME/Library/Application Support/Steam/steamapps/common/A Dance of Fire and Ice}"
ADOFAI_MODS_DIR="${ADOFAI_MODS_DIR:-$ADOFAI_DIR/Mods}"
ADOFAI_MANAGED="${ADOFAI_MANAGED:-$ADOFAI_DIR/ADanceOfFireAndIce.app/Contents/Resources/Data/Managed}"

DOTNET_ROOT="${DOTNET_ROOT:-$HOME/.dotnet}"
DOTNET_ROOT_ARM64="${DOTNET_ROOT_ARM64:-$DOTNET_ROOT}"
DOTNET_EXE="${DOTNET_EXE:-$DOTNET_ROOT/dotnet}"

UNITY_MOD_MANAGER_DLL="${UNITY_MOD_MANAGER_DLL:-$ADOFAI_MANAGED/UnityModManager/UnityModManager.dll}"
HARMONY_DLL="${HARMONY_DLL:-$ADOFAI_MANAGED/UnityModManager/0Harmony.dll}"

REMOVE_COUNTDOWN_BUILD_OUTPUT="${REMOVE_COUNTDOWN_BUILD_DIR:-$REMOVE_COUNTDOWN_PROJECT_ROOT/build/RemoveCountdown}"
REMOVE_COUNTDOWN_ASSET_SOURCE="$REMOVE_COUNTDOWN_PROJECT_ROOT/RemoveCountdown/Assets"
REMOVE_COUNTDOWN_BOOTSTRAP_BUILD_OUTPUT="${REMOVE_COUNTDOWN_BOOTSTRAP_BUILD_DIR:-$REMOVE_COUNTDOWN_PROJECT_ROOT/build/RemoveCountdown.Bootstrap}"
REMOVE_COUNTDOWN_UPDATE_ENGINE_BUILD_OUTPUT="${REMOVE_COUNTDOWN_UPDATE_ENGINE_BUILD_DIR:-$REMOVE_COUNTDOWN_PROJECT_ROOT/build/RemoveCountdown.UpdateEngine}"
REMOVE_COUNTDOWN_INSTALL_PATH="${REMOVE_COUNTDOWN_INSTALL_DIR:-$ADOFAI_MODS_DIR/RemoveCountdown}"
REMOVE_COUNTDOWN_PACKAGE_BUILD_ROOT="${REMOVE_COUNTDOWN_PACKAGE_ROOT:-$REMOVE_COUNTDOWN_PROJECT_ROOT/build/package}"
REMOVE_COUNTDOWN_PACKAGE_STAGE="$REMOVE_COUNTDOWN_PACKAGE_BUILD_ROOT/RemoveCountdown"
REMOVE_COUNTDOWN_PACKAGE_ZIP_PATH="${REMOVE_COUNTDOWN_PACKAGE_ZIP:-$REMOVE_COUNTDOWN_PROJECT_ROOT/build/RemoveCountdown.zip}"
REMOVE_COUNTDOWN_UPDATE_MANIFEST_PATH="${REMOVE_COUNTDOWN_UPDATE_MANIFEST:-$REMOVE_COUNTDOWN_PROJECT_ROOT/build/RemoveCountdown.update.json}"

export REMOVE_COUNTDOWN_PROJECT_ROOT
export ADOFAI_DIR ADOFAI_MODS_DIR ADOFAI_MANAGED
export DOTNET_ROOT DOTNET_ROOT_ARM64 DOTNET_EXE
export UNITY_MOD_MANAGER_DLL HARMONY_DLL
export REMOVE_COUNTDOWN_BUILD_OUTPUT REMOVE_COUNTDOWN_ASSET_SOURCE REMOVE_COUNTDOWN_INSTALL_PATH
export REMOVE_COUNTDOWN_BOOTSTRAP_BUILD_OUTPUT REMOVE_COUNTDOWN_UPDATE_ENGINE_BUILD_OUTPUT
export REMOVE_COUNTDOWN_PACKAGE_BUILD_ROOT REMOVE_COUNTDOWN_PACKAGE_STAGE
export REMOVE_COUNTDOWN_PACKAGE_ZIP_PATH REMOVE_COUNTDOWN_UPDATE_MANIFEST_PATH
